This is my pandas assignment AI generated for me that I did.

In [2]:
import pandas as pd

data = {
    'Student': ['Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Sophia'],
    'Age': [20, 21, 19, 22, 20, 21],
    'Major': ['Math', 'Physics', 'Biology', 'Math', 'History', 'Physics'],
    'Grade': [88, 92, 79, 95, 85, 90],
    'Graduated': [False, False, False, True, False, True]
}

df = pd.DataFrame(data)

In [3]:
df

  Student  Age    Major  Grade  Graduated
0    Emma   20     Math     88      False
1    Liam   21  Physics     92      False
2  Olivia   19  Biology     79      False
3    Noah   22     Math     95       True
4     Ava   20  History     85      False
5  Sophia   21  Physics     90       True

Tasks
Save the DataFrame to:
    CSV
    Excel
Load the files back into pandas.

Practice Methods
    df.to_csv()
    df.to_excel()
    pd.read_csv()
    pd.read_excel()

In [4]:
df.to_csv('df.csv', index=False)
df.to_excel('df.xlsx', index=False)

In [5]:
df_csv = pd.read_csv('df.csv')
df_xlsx = pd.read_excel('df.xlsx')

print(df_csv)
print(df_xlsx)

  Student  Age    Major  Grade  Graduated
0    Emma   20     Math     88      False
1    Liam   21  Physics     92      False
2  Olivia   19  Biology     79      False
3    Noah   22     Math     95       True
4     Ava   20  History     85      False
5  Sophia   21  Physics     90       True
  Student  Age    Major  Grade  Graduated
0    Emma   20     Math     88      False
1    Liam   21  Physics     92      False
2  Olivia   19  Biology     79      False
3    Noah   22     Math     95       True
4     Ava   20  History     85      False
5  Sophia   21  Physics     90       True

Part 3 — Exploring the DataFrame

Tasks
Write code to:
    Show the first 3 rows
    Show the last 2 rows
    Display column names
    Display row indices
    Show summary statistics
    Show data types and non-null counts

Practice Methods
    head()
    tail()
    columns
    index
    describe()
    info()

In [6]:
print(df.head(3), "\n")

print(df.tail(2), "\n")

print(df.columns, "\n")

print(df.index, "\n")

print(df.describe(), "\n")

print(df.info(), "\n")

  Student  Age    Major  Grade  Graduated
0    Emma   20     Math     88      False
1    Liam   21  Physics     92      False
2  Olivia   19  Biology     79      False

  Student  Age    Major  Grade  Graduated
4     Ava   20  History     85      False
5  Sophia   21  Physics     90       True

Index(['Student', 'Age', 'Major', 'Grade', 'Graduated'], dtype='object')

RangeIndex(start=0, stop=6, step=1)

             Age      Grade
count   6.000000   6.000000
mean   20.500000  88.166667
std     1.048809   5.636193
min    19.000000  79.000000
25%    20.000000  85.750000
50%    20.500000  89.000000
75%    21.000000  91.500000
max    22.000000  95.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Student    6 non-null      object
 1   Age        6 non-null      int64
 2   Major      6 non-null      object
 3   Grade      6 non-null      int64
 4   Graduated  6 non-null      bool
dtypes: bool(1), int64(2), object(2)
memory usage: 330.0+ bytes
None

Part 4
The instructions are in instructions.txt

In [7]:
df['Student']

0      Emma
1      Liam
2    Olivia
3      Noah
4       Ava
5    Sophia
Name: Student, dtype: object

In [8]:
df[['Student', 'Grade']]

  Student  Grade
0    Emma     88
1    Liam     92
2  Olivia     79
3    Noah     95
4     Ava     85
5  Sophia     90

In [9]:
df.iloc[0]

Student       Emma
Age             20
Major         Math
Grade           88
Graduated    False
Name: 0, dtype: object

In [ ]:
df.loc[2]

Student       Olivia
Age               19
Major        Biology
Grade             79
Graduated      False
Name: 2, dtype: object

In [11]:
mask = (df['Student'] == 'Sophia')
df.loc[mask, 'Major']

5    Physics
Name: Major, dtype: object

.loc “signature”
.loc is a label-based indexer, not a normal method, but you can think of it like:

df.loc[row_indexer]

df.loc[row_indexer, col_indexer]

Part 5 - Filtering

In [13]:
mask = (df['Age']>20)
df.loc[mask, 'Student']

1      Liam
3      Noah
5    Sophia
Name: Student, dtype: object

In [14]:
mask = (df['Grade']>90)
df.loc[mask, 'Student']

1    Liam
3    Noah
Name: Student, dtype: object

In [15]:
df.loc[df['Major']=='Physics']

  Student  Age    Major  Grade  Graduated
1    Liam   21  Physics     92      False
5  Sophia   21  Physics     90       True

In [16]:
mask = (df['Age']>20) & (df['Grade']>90)
df.loc[mask, 'Student']

1    Liam
3    Noah
Name: Student, dtype: object

In [17]:
df.loc[df['Student'].str.startswith("A")]

  Student  Age    Major  Grade  Graduated
4     Ava   20  History     85      False

In [19]:
df.loc[df['Major'].isin(['Math','Physics'])]

  Student  Age    Major  Grade  Graduated
0    Emma   20     Math     88      False
1    Liam   21  Physics     92      False
3    Noah   22     Math     95       True
5  Sophia   21  Physics     90       True

In [23]:
df.loc[(df['Major']=='Math') | (df['Major']=='Physics')]

  Student  Age    Major  Grade  Graduated
0    Emma   20     Math     88      False
1    Liam   21  Physics     92      False
3    Noah   22     Math     95       True
5  Sophia   21  Physics     90       True

In [21]:
df.loc[~(df['Major']=='Biology')]

  Student  Age    Major  Grade  Graduated
0    Emma   20     Math     88      False
1    Liam   21  Physics     92      False
3    Noah   22     Math     95       True
4     Ava   20  History     85      False
5  Sophia   21  Physics     90       True

Part 6

In [25]:
new_row = {
    'Student': 'Mason',
    'Age': 23,
    'Major': 'Chemistry',
    'Grade': 87,
    'Graduated': False
}

new_row = pd.DataFrame([new_row])

df = pd.concat([df, new_row], ignore_index=True)

In [26]:
df

  Student  Age      Major  Grade  Graduated
0    Emma   20       Math     88      False
1    Liam   21    Physics     92      False
2  Olivia   19    Biology     79      False
3    Noah   22       Math     95       True
4     Ava   20    History     85      False
5  Sophia   21    Physics     90       True
6   Mason   23  Chemistry     87      False

In [29]:
df.iloc[0]

Student       Emma
Age             20
Major         Math
Grade           88
Graduated    False
Name: 0, dtype: object

In [30]:
df.loc[df['Student']=='Ava', 'Grade'] = 91
df['Major'] = df['Major'].str.upper()
df

  Student  Age      Major  Grade  Graduated
0    Emma   20       MATH     88      False
1    Liam   21    PHYSICS     92      False
2  Olivia   19    BIOLOGY     79      False
3    Noah   22       MATH     95       True
4     Ava   20    HISTORY     91      False
5  Sophia   21    PHYSICS     90       True
6   Mason   23  CHEMISTRY     87      False

In [31]:
df = df[df['Student'] != 'Olivia']
df

  Student  Age      Major  Grade  Graduated
0    Emma   20       MATH     88      False
1    Liam   21    PHYSICS     92      False
3    Noah   22       MATH     95       True
4     Ava   20    HISTORY     91      False
5  Sophia   21    PHYSICS     90       True
6   Mason   23  CHEMISTRY     87      False

In [32]:
df = df.drop(columns='Graduated')
df

  Student  Age      Major  Grade
0    Emma   20       MATH     88
1    Liam   21    PHYSICS     92
3    Noah   22       MATH     95
4     Ava   20    HISTORY     91
5  Sophia   21    PHYSICS     90
6   Mason   23  CHEMISTRY     87

In [33]:
df = df.loc[df['Grade']>=85]
df

  Student  Age      Major  Grade
0    Emma   20       MATH     88
1    Liam   21    PHYSICS     92
3    Noah   22       MATH     95
4     Ava   20    HISTORY     91
5  Sophia   21    PHYSICS     90
6   Mason   23  CHEMISTRY     87

In [36]:
dirty_data = {
    'Student': ['Emma', 'Liam', None, 'Noah'],
    'Age': [20, None, 19, 22],
    'Major': ['Math', 'Physics', 'Biology', None],
    'Grade': [88, 92, None, 95]
}

dirty_df = pd.DataFrame(dirty_data)
dirty_df

  Student   Age    Major  Grade
0    Emma  20.0     Math   88.0
1    Liam   NaN  Physics   92.0
2    None  19.0  Biology    NaN
3    Noah  22.0     None   95.0

In [38]:
print(dirty_df.isnull().sum())
dirty_df = dirty_df.dropna()
dirty_df

Student    1
Age        1
Major      1
Grade      1
dtype: int64

  Student   Age Major  Grade
0    Emma  20.0  Math   88.0

In [39]:
dirty_data = {
    'Student': ['Emma', 'Liam', None, 'Noah'],
    'Age': [20, None, 19, 22],
    'Major': ['Math', 'Physics', 'Biology', None],
    'Grade': [88, 92, None, 95]
}

dirty_df = pd.DataFrame(dirty_data)
dirty_df

  Student   Age    Major  Grade
0    Emma  20.0     Math   88.0
1    Liam   NaN  Physics   92.0
2    None  19.0  Biology    NaN
3    Noah  22.0     None   95.0

In [44]:
dirty_df['Age'] = dirty_df['Age'].fillna(0)
dirty_df['Major'] = dirty_df['Major'].fillna("Unknown")
dirty_df = dirty_df.rename(columns={'Grade':'Score'})
dirty_df['Score'] = dirty_df['Score'].astype(float)
dirty_df

  Student   Age    Major  Score
0    Emma  20.0     Math   88.0
1    Liam   0.0  Physics   92.0
2    None  19.0  Biology    NaN
3    Noah  22.0  Unknown   95.0

groupby() in pandas is one of the most important tools for data analysis. It lets you split your data into groups, apply a calculation to each group, and combine the results back together.

Think of it like:

“Put similar rows together, then run math on each group separately.”

📊 What groupby() does

When you do:

df.groupby('Major')

pandas:

Splits the DataFrame into groups based on unique values in "Major"
Creates separate mini-DataFrames for each group
Lets you apply functions to each group

🧠 Basic structure

df.groupby('column')[target_column].function()

In [45]:
df.groupby('Major').size()

Major
CHEMISTRY    1
HISTORY      1
MATH         2
PHYSICS      2
dtype: int64

In [46]:
dirty_df.groupby('Major')['Score'].mean()

Major
Biology     NaN
Math       88.0
Physics    92.0
Unknown    95.0
Name: Score, dtype: float64

In [49]:
dirty_df = dirty_df.sort_values(by='Score', ascending=False)
dirty_df

  Student   Age    Major  Score
3    Noah  22.0  Unknown   95.0
1    Liam   0.0  Physics   92.0
0    Emma  20.0     Math   88.0
2    None  19.0  Biology    NaN

In [50]:
dirty_df['Score'].max()

np.float64(95.0)

In [51]:
dirty_df['Score'].min()

np.float64(88.0)

In [52]:
dirty_df['Age'].mean()

np.float64(15.25)

In [53]:
dirty_df.sort_values(by='Score', ascending=False).head(3)

  Student   Age    Major  Score
3    Noah  22.0  Unknown   95.0
1    Liam   0.0  Physics   92.0
0    Emma  20.0     Math   88.0

In [58]:
df

  Student  Age      Major  Grade
0    Emma   20       MATH     88
1    Liam   21    PHYSICS     92
3    Noah   22       MATH     95
4     Ava   20    HISTORY     91
5  Sophia   21    PHYSICS     90
6   Mason   23  CHEMISTRY     87

In [59]:
import pandas as pd

data = {
    'Student': ['Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Sophia'],
    'Age': [20, 21, 19, 22, 20, 21],
    'Major': ['Math', 'Physics', 'Biology', 'Math', 'History', 'Physics'],
    'Grade': [88, 92, 79, 95, 85, 90],
    'Graduated': [False, False, False, True, False, True]
}

df = pd.DataFrame(data)

In [61]:
df.loc[df['Graduated']==True, 'Grade'].mean()

np.float64(92.5)

In [62]:
df['Passed'] = df['Grade']>=85
df

  Student  Age    Major  Grade  Graduated  Passed
0    Emma   20     Math     88      False    True
1    Liam   21  Physics     92      False    True
2  Olivia   19  Biology     79      False   False
3    Noah   22     Math     95       True    True
4     Ava   20  History     85      False    True
5  Sophia   21  Physics     90       True    True

In [63]:
df['Age_Group'] = 'Uknown'
df.loc[df['Age']<21, 'Age_Group'] = "Young"
df.loc[df['Age']>=21, 'Age_Group'] = "Adult"
df

  Student  Age    Major  Grade  Graduated  Passed Age_Group
0    Emma   20     Math     88      False    True     Young
1    Liam   21  Physics     92      False    True     Adult
2  Olivia   19  Biology     79      False   False     Young
3    Noah   22     Math     95       True    True     Adult
4     Ava   20  History     85      False    True     Young
5  Sophia   21  Physics     90       True    True     Adult